myblog/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contacts/', include("posts.urls", namespace='posts')),
    #url(r'^posts/$', "appname.views.function_name"),
    
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin


from .views import(
	post_create,
	post_detail,
	post_list,
	post_update,
	post_delete,
	login_user,
	logout_user,
	register_user,
	contact_download,
	) 


urlpatterns = [
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<id>\d+)/$', post_detail, name='details'),
    url(r'^list/$', post_list, name='list'),
    # url(r'^drafts/$', post_drafts, name='drafts'),
    url(r'^(?P<id>\d+)/edit/$', post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', post_delete),
##############
	url(r'^login/$', login_user, name="login"),
	url(r'^logout/$', logout_user, name="logout"),
	url(r'^register/$', register_user, name="register"),
	url(r'^download-csv/$', contact_download, name="contact_download"),

	# path('download-csv/', contact_download, name='contact_download'),
	# url(r'^myposts/$', my_posts, name="myposts"),
 #############

    #url(r'^posts/$', "appname.views.function_name"),
    
]

posts/models.py
from django.conf import settings
from django.db import models



def upload_location(instance, filename):
	return "blog%s_%s" %(instance.id,filename)

	
class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)

	fullname = models.CharField(max_length=120, default="N/A")
	nickname = models.CharField(max_length=120, default="N/A")
	email =  models.CharField(max_length=120, default="N/A")
	phone = models.CharField(max_length=20, default="N/A")
	address = models.TextField(default="N/A")

	image = models.ImageField(
		upload_to=upload_location,
		null=True,
		blank=True)

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	class Meta:
		ordering  = ["fullname"]
# 		order by reverse id,timestamp,updated

posts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms

from .models import Post


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
			"fullname",
			"nickname",
			"email",
			"phone",
			"address",
			"image",
		]



class SignUpForm(UserCreationForm):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=100)
	last_name = forms.CharField(max_length=100)

	class Meta:
		model = User
		fields = ("username","first_name","last_name","email","password1","password2",)

		

posts/views.py
from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.db.models import Q
from django.shortcuts import render,redirect, get_object_or_404, redirect
from django.utils import timezone
from django.shortcuts import HttpResponse
import csv
# Create your views here.
from .forms import PostForm, SignUpForm
from .models import Post

#####################

# from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 

#####################

def post_list(request):
	if not request.user.is_authenticated():
		messages.error(request, "You are not logged in")
		return redirect("posts:login")

	queryset_list = Post.objects.filter(user = request.user )


	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(fullname__icontains=query)|
			Q(phone__icontains=query)|
			Q(address__icontains=query)|
			Q(nickname__icontains=query)
		).distinct()

	#queryset_list = Post.objects.all() #.order_by("-timestamp")
	paginator = Paginator(queryset_list, 4) #show how many blogs

	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		#if page not integer deliver first page
		queryset = paginator.page(1)
	except EmptyPage:
		# if page out of range deliver last one
		queryset = paginator.page(paginator.num_pages)

	context = {
			"object_list": queryset,
			"title": "Contacts",
	}

	return render(request, "post_list.html", context)

##########################

def login_user(request):
	if request.method == 'POST':
		username = request.POST['Username']
		password = request.POST['Password']
		user = authenticate( username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, ('Login Successful!'))
			return redirect('posts:list')	
		else:
			messages.success(request, ('Error! Incorrect Username or Password'))
			return redirect('posts:login')
	else:
		return render(request, 'login.html', {})


###################

def logout_user(request):
	logout(request)
	messages.success(request, ('Successfully Logged Out!'))
	return render(request, 'edit.html', {})

##################

def register_user(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username=username,password=password)
			login(request, user)
			messages.success(request, ('Registration Successful'))
			return redirect('posts:list')
	else:
		form = SignUpForm()

	context = {'form': form}

	return render(request, 'register.html',context)



def post_create(request):
	if not request.user.is_authenticated():
		messages.error(request, "You are not logged in")
		return redirect("posts:list")


	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()

		messages.success(request, "Succesfully Created")
		return redirect("posts:list")

	context = {
		"form" : form,
	}
	return render(request, "post_form.html", context)



def post_detail(request, id=None):
	instance = get_object_or_404(Post, id=id)
	if not request.user.is_authenticated():
		messages.error(request, "You are not logged in")
		return redirect("posts:login")

	context = {
		"title": "Details",
		"instance": instance
	}
	return render(request, "post_detail.html", context)



# def post_drafts(request):
# 	if not request.user.is_authenticated():
# 		messages.error(request, "You are not logged in")
# 		return redirect("posts:list")

# 	queryset_list = Post.objects.filter(draft=True)

# 	query = request.GET.get("q")

# 	if query:
# 		queryset_list = queryset_list.filter(
# 			Q(title__icontains=query)|
# 			Q(content__icontains=query)
# 		).distinct()

# #	queryset_list = Post.objects.all() #.order_by("-timestamp")
# 	paginator = Paginator(queryset_list, 5) #show how many blogs

# 	page = request.GET.get('page')
# 	try:
# 		queryset = paginator.page(page)
# 	except PageNotAnInteger:
# 		#if page not integer deliver first page
# 		queryset = paginator.page(1)
# 	except EmptyPage:
# 		# if page out of range deliver last one
# 		queryset = paginator.page(paginator.num_pages)

# 	context = {
# 			"object_list": queryset,
# 			"title": "List",
# 	}

# 	return render(request, "edit.html", context)

# # copy paginator view def listing()

def post_update(request, id=None):
	if not request.user.is_authenticated():
		messages.error(request, "You do not have permission")
		return redirect("posts:list")

	instance = get_object_or_404(Post, id=id)

	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	context = {
		"title": "Update Contact",
		"instance": instance,
		"form": form,
	}

	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()

		messages.success(request, "Update Succesfull")

		return redirect("posts:list")

	
	return render(request, "post_form.html", context)

def post_delete(request, id=None):
	if not request.user.is_authenticated():
		messages.error(request, "You are not logged in")
		return redirect("posts:list")
	instance = get_object_or_404(Post, id=id)
	instance.delete()
	messages.success(request, "Succesfully Deleted !")

	return redirect("posts:list")


########################

def contact_download(request):
	if not request.user.is_authenticated():
		messages.error(request, "You do not have permission")
		return redirect("posts:list")

	items = Post.objects.filter(user = request.user)

	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="contact.csv"'

	writer = csv.writer(response, delimiter=',')
	writer.writerow(['fullname',  'nickname',  'email',  'phone',  'address'])

	for obj in items:
		writer.writerow([obj.fullname, obj.nickname, obj.email, obj.phone, obj.address])

	return response

templates/base.html
{% load staticfiles %}
<!--Doctype html -->

<html>
<head>
	<title>Contacts</title>

  <!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
<!-- Facebook -->
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2';
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>
<!--  -->


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>

 	<a class="navbar-brand" href="{% url 'posts:list' %}">Addressbook</a>

	<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">

      {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:create' %}">Add New</a>
          </li>

         <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:contact_download' %}">Download</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:logout' %}">Logout</a>
          </li>
          <a class="navbar-brand" style="color:#52BE80;"> User: {{user.username}}</a>
          
      {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:register' %}">Register</a>
          </li>

      {% endif %}
    </ul>

    </div>
 </nav>

 <div class="container">
    {% if messages %}
       {% for message in messages %}
          <div class="alert alert-warning alert-dismissable" role="alert">
              <button class="close" data-dismiss="alert">
                  <small><sup>x</sup></small>
              </button>
              {{ message }}
          </div>
       {% endfor %}
    {% endif %}




{% block content %}
<!-- All contents will be shown here -->
{% endblock content %}

<!-- Latest compiled and minified JavaScript -->
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

templates/edit.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

templates/login.html
{% extends "base.html" %}

 {% block content %}

	<h1 class="text-center">Login</h1>

<div class="col-md-6 offset-md-3">
	<form method="POST">
		{% csrf_token %}
	  <div class="form-group">
	    <label >Username</label>
	    <input type="text" class="form-control" placeholder="Enter Username" name="Username">
	  </div>

	  <div class="form-group">
	    <label>Password</label>
	    <input type="password" class="form-control" placeholder="Enter Password" name="Password">
	  </div>

	  <button type="submit" class="btn btn-primary">LOGIN</button>
	</form>
</div>

{% endblock%}

templates/message_display.html
{% if messages %}
	<div class="messages">
		<ul class="messages">
		    {% for message in messages %}
		    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		    {% endfor %}
		</ul>
	</div>
{% endif %}

templates/post_detail.html
{% extends "base.html" %}

{% block head_title %} 
{{instance.title}} || {{block.super}} 
{% endblock head_title %}

{% block content %} 


<div class='col-sm-6 col-sm-offset-3' style="margin: auto;">
	<h1>{{ title }}</h1>
	
	<img style=" border-radius: 20px;height: 200px; margin: auto; margin-bottom: 5px; margin-top: 15px;" src="{{ instance.image.url }}" class="img-responsive"/>

	<h3>{{ instance.fullname }}</h3><br/>
	<p>Nickname:    {{ instance.nickname }}</p><br/>
	<p>Phone No:    {{ instance.phone }}</p><br/>
	<p>Email:		{{ instance.email }}</p><br/>
	<p>Address:     {{ instance.address }}</p><br/>

	<a href="/contacts/{{instance.id}}/edit" class="btn btn-primary" role="Edit">Edit</a>

	 <a href="/contacts/{{instance.id}}/delete/" class="btn btn-danger" role="Edit">Delete</a>

		
	</h2>


</div>

{% endblock content %} 

templates/post_form.html
{% extends "base.html" %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3">

	<h1>Form</h1>

	<form method='POST' action='' enctype="multipart/form-data"> 
		{% csrf_token %}
		
		{{form.as_p}} <!-- 	as paragraph -->
		
		<input type='submit' class="btn btn-default" value='Post' />
	</form>

</div>

{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3" style="margin: auto;">
<h1 style="color:#C0C0C0; text-align: center;" class="center">{{ title }}  </h1>


<form method="GET" action='' >
	<input type="text" class="form-control"  name="q" placeholder="Search Contacts" value="{{request.GET.q}}" style="margin: auto;" />
	<input type="submit" value='Search' class="btn btn-dark" style="margin: 20px 50% 20px 45%"/>

</form>

{% for obj in object_list %}
	<div class="row">
		{% if obj.image %}
		<img style=" border-radius: 20px;height: 200px; margin: auto; margin-bottom: 5px; margin-top: 15px;" src="{{ obj.image.url }}" class="img-responsive"/>
		<!-- <div class='col-sm-12'> --> </br>
		{% endif %}

	  <div class="col-sm-12">
		    <div class="thumbnail">
		      <!-- <img src="..." alt="..."> -->
			      <div class="caption">
			        <h3>
			        <a href='/contacts/{{obj.id}}/'>{{obj.fullname}}</a>
			    	</h3>
			        <p>
			        Phone: {{obj.phone}}</br>
			        Email: {{obj.email}}
			    	</p>

			        <p>
				        <a href="/contacts/{{obj.id}}/" class="btn btn-success" role="button">Details</a> 

				        <a href="/contacts/{{obj.id}}/edit" class="btn btn-primary" role="Edit">Edit</a>

				        <a href="/contacts/{{obj.id}}/delete/" class="btn btn-danger" role="Edit">Delete</a>
				    	</p>
	        
			      </div>
		    </div>
	  </div>
	</div>

{% endfor %}

</hr>
</hr>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ object_list.previous_page_number }}">&laquo;  Previous </a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">Next &raquo;</a>
            <a href="?page={{ object_list.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
</div>



</div>

<!-- thumbnail bootstrap copy 26" 5:20 -->
<!--  -->
<!-- copy pagination code -->
{% endblock content %}

templates/register.html
{% extends "base.html" %}

{% block content %}

	 <h2>Register</h2>

	<form method="POST" action="{% url 'posts:register' %}">
		{% csrf_token %}
		{% if form.errors %}
			<p>Your Form Has Errors!!! Please Read The Guidelines Carefully</p>
		{% endif %}

		{{  form.as_ul }}
		<input type="submit" value="Register" class="btn btn-secondary">

	</form>

{% endblock%}